---
# tasks file for iptables (CentOS specific)

- name: Install iptables packages
  yum: name={{ item }} state=present
  with_items: iptables_packages
  tags: iptables

- name: Ensure iptables is started and enabled on boot
  service: name={{ iptables_service_name }} state=started enabled=yes
  tags: iptables
