---
# tasks file for iptables

- name: Create iptables configuration
  template: >
    src=iptables.j2
    dest=/etc/sysconfig/iptables
    owner=root
    group=root
    mode=0600
  notify: restart iptables
  tags: iptables
